package com.skc.swagger.model;

import java.io.Serializable;

import javax.management.Query;
import javax.persistence.*;

import io.swagger.annotations.ApiModelProperty;
import lombok.*;

@Entity
@Table(name = "book")
@Getter
@Setter
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class Book {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(value = "autogenerated id")
    @Column(name = "book_id")
    private int bookId;
    @ApiModelProperty(value = "this is the book name")
    @Column(name = "book_name")
    private String bookName;
    @ApiModelProperty(value = "this is book price")
    private double price;
}
